---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-ovn-dangling-ips
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: kube-ovn-dangling-ips
spec:
  defaultSubnet: kube-ovn-dangling-ips-control-net
  namespaces:
    - kube-ovn-dangling-ips
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: kube-ovn-dangling-ips-control-net
spec:
  vpc: kube-ovn-dangling-ips
  protocol: IPv4
  disableGatewayCheck: true
  cidrBlock: 10.10.0.0/24
  excludeIps:
    - 10.10.0.106
  namespaces:
    - kube-ovn-dangling-ips
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kube-ovn-dangling-ips-control-net
  namespace: kube-ovn-dangling-ips
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "kube-ovn-dangling-ips-control-net.kube-ovn-dangling-ips.ovn"
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-1
  namespace: kube-ovn-dangling-ips
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: test-vm-1
      annotations:
        ovn.kubernetes.io/logical_switch: ovn-default
        kube-ovn-dangling-ips-control-net.kube-ovn-dangling-ips.ovn.kubernetes.io/ip_address: 10.10.0.106
        kube-ovn-dangling-ips-control-net.kube-ovn-dangling-ips.ovn.kubernetes.io/mac_address: "00:00:01:00:00:01"
        kube-ovn-dangling-ips-control-net.kube-ovn-dangling-ips.ovn.kubernetes.io/logical_router: kube-ovn-dangling-ips
        kube-ovn-dangling-ips-control-net.kube-ovn-dangling-ips.ovn.kubernetes.io/logical_switch: kube-ovn-dangling-ips-control-net
    spec:
      nodeSelector:
        kubevirt.io/schedulable: "true"
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: "0-control-net"
            bridge: { }
            macAddress: "00:00:01:00:00:01"
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - name: "0-control-net"
        multus:
          # NOTE: With Kube-OVN, subnet name is resolved based on the network name.
          networkName: "kube-ovn-dangling-ips/kube-ovn-dangling-ips-control-net"
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
